### ISSUE TITLE
can this be flash on a standard MMDVM Modem from Aliexpress

### ISSUE THREAD

**Issue by sysadminpower2019** [g4klx/MMDVM-TNC#2]
Something like the following
https://www.aliexpress.com/item/1005005636431546.html

**Comment by g4klx** [comment]
No, that is not an MMDVM modem board, it is an MMDVM hotspot. A modem board uses an existing FM radio capable of 9600 baud operation.


Sent from Yahoo Mail for iPhone


On Monday, April 15, 2024, 01:04, sysadminpower2019 ***@***.***> wrote:




Something like the following
https://www.aliexpress.com/item/1005005636431546.html
